[package]
name = "pallet-partner-chains-session"
version = "1.0.0"
repository.workspace = true
description = "FRAME pallet for setting validators with InherentData and session management"
edition = "2021"
license = "Apache-2.0"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }
impl-trait-for-tuples = "0.2.2"
log = { workspace = true }
pallet-timestamp = { path = "../timestamp", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive", "serde"] }
sp-core = { path = "../../primitives/core", default-features = false, features = ["serde"] }
sp-runtime = { path = "../../primitives/runtime", default-features = false, features = ["serde"] }
sp-partner-chains-session = { path = "../../primitives/partner-chains-session", default-features = false }
sp-staking = { path = "../../primitives/staking", default-features = false, features = ["serde"] }
sp-std = { path = "../../primitives/std", default-features = false }


[features]
default = ["std", "polkadot-js-compat"]
std = [
	"codec/std",
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "scale-info/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-partner-chains-session/std",
    "sp-staking/std",
    "sp-std/std",
]
polkadot-js-compat = []
